// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = function(name, drunk) {
    if (drunk) {
      return "hello " + name + ",you look sexy today";
    } else {
      return "hello " + name;
    }
  };

}).call(this);
